apiVersion: apps/v1
kind: Deployment
metadata:
  name: sime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sime
  template:
    metadata:
      labels:
        app: sime
    spec:
      containers:
      - image: okteto.dev/sime:latest
        name: sime
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "b6d207e2-f70c-4c22-b0c8-fe19bcfd62b8"
        - name: Vless_Path
          value: "/arg"
        - name: Vmess_UUID
          value: "b6d207e2-f70c-4c22-b0c8-fe19bcfd62b8"
        - name: Vmess_Path
          value: "/arg"
        - name: Share_Path
          value: "/arg"
